trigger:
- main

pool:
  vmImage: 'windows-2019'

stages:
- stage: ApproveAndDeploy
  displayName: Approve and Deploy to Azure App Service
  dependsOn: PushDockerImage
  jobs:
  - job: Deploy
    displayName: Deploy Docker Image to Azure App Service
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: Azure subscription 1
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config container set \
            --name my-docker-app-service \
            --resource-group my-resource-group \
            --docker-custom-image-name paruckerh/mobead_image_build:latest
